spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://192.168.99.100:5432/test?socketTimeout=1&connectTimeout=1
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    validation-query: SELECT 1
    test-while-idle: true
    test-on-borrow: true